settings:
  cache: true
  cache_expiration: 30
  asset_directory: /config/assets
  asset_folders: true
  asset_depth: 1
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: true
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  default_collection_order:
  minimum_items: 2
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  only_filter_missing: false
  show_missing_assets: false
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_report: false
  verify_ssl: true
  check_nightly: false
  custom_repo:
  playlist_exclude_users:
webhooks:
  error: notifiarr
  version: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
  delete:
notifiarr:
  apikey: (redacted)
plex:
  url: (redacted)
  token: (redacted)
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: false
trakt:
  client_id: (redacted)
  client_secret: (redacted)
  pin:
  authorization:
    access_token: (redacted)
    token_type: Bearer
    expires_in: (redacted)
    refresh_token: (redacted)
    scope: public
    created_at: (redacted)
mdblist:
  apikey: (redacted)
  cache_expiration: 60
tmdb:
  apikey: (redacted)
  language: en
  cache_expiration: 60
  region: GB
omdb:
  apikey: (redacted)
  cache_expiration: 60
radarr:
  url: http://radarr-4k:7878
  token: (redacted)
  add_missing: true
  add_existing: true
  root_folder_path: /data/media/4k-movies
  monitor: true
  availability: released
  quality_profile: 4K Movies
  tag: pmm
  search: true
  radarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false
libraries:
  Movies:
    report_path: /config/reports/movies.yml
    metadata_path:
    - folder: config/metadata/movies/
    - pmm: seasonal
      template_variables:
        use_valentine: false
        use_independence: false
        use_thanksgiving: false
        use_mother: false
        use_memorial: false
        use_father: false
        use_labor: false
        sort_by: title.asc
        radarr_add_missing: false
        radarr_tag: pmm_seasonal
        item_radarr_tag: pmm_seasonal
        tmdb_collection_halloween:
        - 11716     # Addams Family
        - 313086    # Conjuring
        - 91361     # Halloween Collection
        - 8581      # A Nightmare on Elm Street Collection
        - 1733      # The Mummy Collection
        - 8091      # Alien Collection
        - 2980      # Ghostbusters
        - 751156    # Hocus Pocus
        tmdb_movie_halloween:
        - 23437     # A Nightmare on Elm Street (2010)
        imdb_list_halloween: anything
        radarr_add_missing_halloween: true
        radarr_tag_halloween: pmm_halloween
        item_radarr_tag_halloween: pmm_halloween
        schedule_mother: range(03/17-03/22)
    - pmm: separator_award
    - pmm: oscars
      template_variables:
        use_best_director: false
        use_year_collections: false
        collection_order: release
        radarr_tag: pmm_oscars
        item_radarr_tag: pmm_oscars
    # - pmm: separator_chart
    - pmm: basic
      template_variables:
        sort_by: title.asc
        radarr_tag: pmm_basic
    - pmm: imdb
      template_variables:
        use_popular: false
        use_lowest: false
        radarr_tag: pmm_imdb_250
        item_radarr_tag: pmm_imdb_250
    - pmm: decade
      template_variables:
        sort_by: critic_rating.desc
        radarr_tag: pmm_decade
        collection_section: 999
    # - pmm: flixpatrol
      # template_variables:
        # location_netflix: united_kingdom
        # location_disney: united_kingdom
        # location_hbo: world
        # location_hulu: world
        # location_paramount: world
        # location_prime: united_kingdom
        # radarr_tag: pmm_flixpatrol
        # item_radarr_tag: pmm_flixpatrol
        # radarr_monitor: none
        # radarr_search: false
    overlay_path:
    # - reset_overlays: tmdb                          # if you want to reset the poster to default poster from tmdb
    - remove_overlays: false                     # Set to true if you want to remove overlays
    - reapply_overlay: false                        # If you are doing a lot of testing and changes like me, keep this to true to always reapply overlays
    - pmm: mediastinger
    - pmm: resolution
      template_variables:
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_extended: false
        use_uncut: false
        use_unrated: false
        use_special: false
        use_anniversary: false
        use_collector: false
        use_diamond: false
        use_platinum: false
        use_directors: false
        use_final: false
        use_international: false
        use_theatrical: false
        use_ultimate: false
        use_alternate: false
        use_coda: false
        use_remastered: false
        use_criterion: false
        use_richarddonner: false
        use_blackchrome: false
        use_definitive: false
        use_ulysses: false
    - file: config/overlays/movies/content_rating.yml
    operations:
      assets_for_all: true
      # mass_poster_update: tmdb
      delete_collections:
        configured: false
        managed: false
      content_rating_mapper:
        G: gb/U
        TV-G: gb/U
        PG: gb/PG
        gb/A: gb/PG
        gb/9+: gb/PG
        TV-PG: gb/PG
        gb/12A: gb/12
        PG-13: gb/12
        R: gb/15
        TV-14: gb/15
        gb/16: gb/15
        gb/AA: gb/15
        gb/X: gb/18
        TV-MA: gb/18
        None: gb/Not Rated
        Not Rated: gb/Not Rated
        NR: gb/Not Rated

  Movies for operations:
    library_name: Movies
    schedule: Weekly(monday)
    operations:
      mass_genre_update: tmdb
      # mass_poster_update: tmdb
      # mass_content_rating_update: reset
      mass_originally_available_update: tmdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: imdb
      split_duplicates: false
      metadata_backup:
        path: /config/backups/Movies/metadata.yml

  TV Shows:
    report_path: /config/reports/TV_Shows.yml
    overlay_path:
    # - reset_overlays: tmdb                          # if you want to reset the poster to default poster from tmdb
    - remove_overlays: false                        # Set to true if you want to remove overlays
    - reapply_overlay: true                        # If you are doing a lot of testing and changes like me, keep this to true to always reapply overlays
    - pmm: resolution
      template_variables:
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_edition: false
    - pmm: resolution
      template_variables:
        overlay_level: season
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_edition: false
    operations:
      assets_for_all: true
      content_rating_mapper:
        G: gb/U
        TV-G: gb/U
        PG: gb/PG
        gb/A: gb/PG
        gb/12A: gb/12
        PG-13: gb/12
        R: gb/15
        TV-14: gb/15
        gb/16: gb/15
        gb/AA: gb/15
        gb/X: gb/18
        TV-MA: gb/18
      mass_genre_update: tmdb
      # mass_poster_update: tmdb
      # mass_content_rating_update: reset
      mass_originally_available_update: tmdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: tmdb
      split_duplicates: false
      metadata_backup:
        path: /config/backups/TV/metadata.yml

playlist_files:
- pmm: playlist
  template_variables:
    use_arrow: false
    use_dcau: false
    use_pokemon: false
    use_clonewars: false
    use_dragonball: false
    radarr_add_missing: false
